import { action } from "./_generated/server";
import { internal } from "./_generated/api";

export const seed = action({
  args: {},
  handler: async (ctx) => {
    const sampleBusinesses = [
      {
        name: "Cairo Coffee House",
        description: "Established coffee shop in the heart of Zamalek with loyal customer base. Features outdoor seating, premium coffee equipment, and a prime location near embassies and hotels.",
        category: "restaurant",
        price: 2500000,
        revenue: 800000,
        profit: 250000,
        location: "Zamalek, Cairo",
        employees: 8,
        yearEstablished: 2018,
        reason: "Owner relocating abroad for family reasons",
        images: ["https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800"],
        contactEmail: "owner@cairocoffee.eg",
        contactPhone: "+20 100 123 4567",
      },
      {
        name: "Alexandria Seafood Restaurant",
        description: "Popular seafood restaurant on the Corniche with stunning Mediterranean views. Fully equipped kitchen, established supplier relationships, and excellent reputation.",
        category: "restaurant",
        price: 4500000,
        revenue: 1800000,
        profit: 600000,
        location: "Alexandria",
        employees: 15,
        yearEstablished: 2015,
        reason: "Owner pursuing other business ventures",
        images: ["https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800"],
        contactEmail: "contact@alexseafood.eg",
        contactPhone: "+20 100 234 5678",
      },
      {
        name: "Fashion Boutique - New Cairo",
        description: "Trendy fashion boutique in a premium mall location. Strong social media presence, established brand, and loyal customer base. Includes inventory and fixtures.",
        category: "retail",
        price: 1800000,
        revenue: 1200000,
        profit: 350000,
        location: "New Cairo",
        employees: 5,
        yearEstablished: 2019,
        reason: "Owner starting new business in different industry",
        images: ["https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800"],
        contactEmail: "info@fashionboutique.eg",
        contactPhone: "+20 100 345 6789",
      },
      {
        name: "Digital Marketing Agency",
        description: "Full-service digital marketing agency with 20+ active clients including major Egyptian brands. Experienced team, proven track record, and recurring revenue model.",
        category: "services",
        price: 3200000,
        revenue: 2400000,
        profit: 800000,
        location: "Maadi, Cairo",
        employees: 12,
        yearEstablished: 2017,
        reason: "Founder retiring",
        images: ["https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800"],
        contactEmail: "hello@digitalagency.eg",
        contactPhone: "+20 100 456 7890",
      },
      {
        name: "Gym & Fitness Center",
        description: "Modern gym with 300+ active members in Heliopolis. Includes all equipment, group class studio, and personal training services. Strong membership retention rate.",
        category: "services",
        price: 5500000,
        revenue: 2200000,
        profit: 750000,
        location: "Heliopolis, Cairo",
        employees: 10,
        yearEstablished: 2016,
        reason: "Owner moving to another city",
        images: ["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800"],
        contactEmail: "info@fitnesscenter.eg",
        contactPhone: "+20 100 567 8901",
      },
      {
        name: "Printing & Packaging Factory",
        description: "Established printing facility with modern equipment serving corporate clients. Long-term contracts with major companies, skilled workforce, and growth potential.",
        category: "manufacturing",
        price: 8000000,
        revenue: 5000000,
        profit: 1500000,
        location: "6th of October City",
        employees: 25,
        yearEstablished: 2012,
        reason: "Partnership dissolution",
        images: ["https://images.unsplash.com/photo-1590859808308-3d2d9c515b1a?w=800"],
        contactEmail: "sales@printingfactory.eg",
        contactPhone: "+20 100 678 9012",
      },
      {
        name: "Luxury Spa & Wellness Center",
        description: "High-end spa in a premium location offering massage, beauty treatments, and wellness services. Established clientele of affluent customers, modern facilities, and experienced staff.",
        category: "services",
        price: 3800000,
        revenue: 1600000,
        profit: 550000,
        location: "Sheikh Zayed, Giza",
        employees: 14,
        yearEstablished: 2018,
        reason: "Owner focusing on international expansion",
        images: ["https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800"],
        contactEmail: "info@luxuryspa.eg",
        contactPhone: "+20 100 789 0123",
      },
      {
        name: "Organic Grocery Store",
        description: "Popular organic and health food store with growing customer base. Prime location, established supplier network, and strong online presence with delivery service.",
        category: "retail",
        price: 2200000,
        revenue: 1400000,
        profit: 420000,
        location: "Dokki, Cairo",
        employees: 9,
        yearEstablished: 2019,
        reason: "Owner relocating for personal reasons",
        images: ["https://images.unsplash.com/photo-1542838132-92c53300491e?w=800"],
        contactEmail: "contact@organicstore.eg",
        contactPhone: "+20 100 890 1234",
      },
      {
        name: "Private Language School",
        description: "Established language center teaching English, French, and German. Certified instructors, modern teaching facilities, and strong reputation with consistent enrollment.",
        category: "education",
        price: 4200000,
        revenue: 2000000,
        profit: 700000,
        location: "Nasr City, Cairo",
        employees: 18,
        yearEstablished: 2014,
        reason: "Founder pursuing academic career abroad",
        images: ["https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800"],
        contactEmail: "admin@languageschool.eg",
        contactPhone: "+20 100 901 2345",
      },
      {
        name: "Mobile Phone Repair Chain",
        description: "Three-location mobile repair business with strong brand recognition. Trained technicians, genuine parts inventory, and warranty service. Excellent growth potential.",
        category: "technology",
        price: 1500000,
        revenue: 900000,
        profit: 300000,
        location: "Multiple locations - Cairo",
        employees: 11,
        yearEstablished: 2017,
        reason: "Owner starting new tech venture",
        images: ["https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=800"],
        contactEmail: "business@phonerepair.eg",
        contactPhone: "+20 100 012 3456",
      },
      {
        name: "Dental Clinic",
        description: "Modern dental clinic with state-of-the-art equipment and experienced dentists. Established patient base, insurance partnerships, and excellent location in upscale area.",
        category: "healthcare",
        price: 6500000,
        revenue: 3200000,
        profit: 1100000,
        location: "Mohandessin, Cairo",
        employees: 13,
        yearEstablished: 2013,
        reason: "Doctor retiring from practice",
        images: ["https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=800"],
        contactEmail: "info@dentalclinic.eg",
        contactPhone: "+20 100 123 4568",
      },
      {
        name: "Real Estate Agency",
        description: "Successful real estate brokerage with strong portfolio of properties and established client network. Experienced agents, prime office location, and proven sales record.",
        category: "real-estate",
        price: 2800000,
        revenue: 1800000,
        profit: 650000,
        location: "New Cairo",
        employees: 8,
        yearEstablished: 2016,
        reason: "Owner consolidating multiple businesses",
        images: ["https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800"],
        contactEmail: "sales@realestateagency.eg",
        contactPhone: "+20 100 234 5679",
      },
      {
        name: "Bakery & Pastry Shop",
        description: "Beloved neighborhood bakery known for fresh bread and traditional Egyptian pastries. Loyal customer base, early morning foot traffic, and catering services.",
        category: "restaurant",
        price: 1200000,
        revenue: 750000,
        profit: 220000,
        location: "Heliopolis, Cairo",
        employees: 7,
        yearEstablished: 2015,
        reason: "Owner health issues",
        images: ["https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800"],
        contactEmail: "info@bakeryshop.eg",
        contactPhone: "+20 100 345 6780",
      },
      {
        name: "Car Wash & Detailing Center",
        description: "Premium car care facility with modern equipment and eco-friendly products. Membership program, corporate clients, and excellent location with high traffic.",
        category: "services",
        price: 1900000,
        revenue: 1100000,
        profit: 380000,
        location: "5th Settlement, New Cairo",
        employees: 10,
        yearEstablished: 2018,
        reason: "Owner expanding to new city",
        images: ["https://images.unsplash.com/photo-1601362840469-51e4d8d58785?w=800"],
        contactEmail: "contact@carwash.eg",
        contactPhone: "+20 100 456 7891",
      },
      {
        name: "Children's Play Center",
        description: "Indoor entertainment venue for children with games, activities, and party hosting. Strong weekend and holiday revenue, established reputation, and repeat customers.",
        category: "services",
        price: 3500000,
        revenue: 1700000,
        profit: 580000,
        location: "Maadi, Cairo",
        employees: 16,
        yearEstablished: 2017,
        reason: "Owner relocating abroad",
        images: ["https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=800"],
        contactEmail: "info@playcenter.eg",
        contactPhone: "+20 100 567 8902",
      },
    ];

    console.log("Seeding database with sample businesses...");
    
    for (const business of sampleBusinesses) {
      await ctx.runMutation(internal.businessesInternal.createInternal, business);
    }

    console.log(`Successfully seeded ${sampleBusinesses.length} businesses!`);
    return { success: true, count: sampleBusinesses.length };
  },
});